import { DEFAULT_CHECKLIST, type ChecklistItem } from './utils/checklist'

export const SEED_ACCOUNTS = [
  {
    name: 'Alex Rivera',
    email: 'admin@specflow.dev',
    password: 'Admin1234!',
    role: 'admin' as const,
    preferences: {
      theme: 'system' as const,
      accent: 'teal' as const,
      density: 'comfortable' as const,
      notifications: {
        taskAssigned: true,
        commentCreated: true,
        mentionCreated: true,
        taskStatus: true,
      },
      defaults: { tasksView: 'list' as const },
    },
  },
  {
    name: 'Jordan Lee',
    email: 'dev@specflow.dev',
    password: 'Dev12345!',
    role: 'developer' as const,
    preferences: {
      theme: 'dark' as const,
      accent: 'amber' as const,
      density: 'compact' as const,
      notifications: {
        taskAssigned: true,
        commentCreated: true,
        mentionCreated: true,
        taskStatus: false,
      },
      defaults: { tasksView: 'board' as const },
    },
  },
]

function daysFromNow(offset: number): Date {
  const date = new Date()
  date.setUTCHours(12, 0, 0, 0)
  date.setUTCDate(date.getUTCDate() + offset)
  return date
}

function checklist(...doneKeys: string[]): ChecklistItem[] {
  return DEFAULT_CHECKLIST.map((item) => ({ ...item, done: doneKeys.includes(item.key) }))
}

export function buildSeedPayload(adminId: string, developerId: string) {
  const specs = [
    {
      title: 'Refresh token rotation',
      businessGoal:
        'Keep sessions short-lived without forcing people to sign in every fifteen minutes when they return to SpecFlow.',
      technicalApproach:
        'Issue a 15-minute access JWT in memory and rotate a 7-day refresh token in an httpOnly cookie. Behind the Vercel `/api` proxy the cookie is first-party (`SameSite=Lax`).',
      apiDesign: 'POST /auth/login · POST /auth/refresh · POST /auth/logout · GET /auth/me',
      edgeCases: [
        'Reuse of a rotated refresh token is rejected via tokenVersion.',
        'Logout increments tokenVersion so outstanding refresh cookies die.',
        'Concurrent refresh requests must not double-bump the version.',
      ],
      acceptanceCriteria: [
        'Access tokens expire in 15 minutes.',
        'Refresh tokens are not readable from JavaScript.',
        'A page reload restores the session when the cookie is valid.',
      ],
      regressionRisks: 'Wrong FRONTEND_URL or cookie flags will silently log everyone out after deploy.',
      status: 'approved' as const,
      createdBy: adminId,
      approvedBy: adminId,
      approvedAt: daysFromNow(-12),
      archivedAt: null as Date | null,
      tasks: [] as unknown[],
    },
    {
      title: 'Spec to board handoff',
      businessGoal: 'Approved specs should spawn trackable work without copy-paste between docs and the board.',
      technicalApproach:
        'Link existing tasks to a spec, keep a bidirectional reference, and show coverage counts on the specs list.',
      apiDesign: 'POST /specs/:id/tasks · GET /specs/:id · DELETE unlinks on task delete',
      edgeCases: [
        'Linking a task already on another spec moves it.',
        'Archived specs stay readable but drop out of the default list.',
      ],
      acceptanceCriteria: [
        'Admins can link an existing task from spec detail.',
        'Task detail shows the linked spec.',
        'Task count on the specs list stays accurate.',
      ],
      regressionRisks: 'Orphaned links if a task is deleted without pulling it from Spec.tasks.',
      status: 'in-review' as const,
      createdBy: adminId,
      approvedBy: null,
      approvedAt: null,
      archivedAt: null,
      tasks: [] as unknown[],
    },
    {
      title: 'Dashboard workload snapshot',
      businessGoal: 'Give each role a clear picture of open work, blockers, and due dates at a glance.',
      technicalApproach:
        'Aggregate open tasks, specs by status, overdue/due-soon, blocked counts, and completed-this-week. Developers only see their own open work.',
      apiDesign: 'GET /dashboard returns totals, specsByStatus, and deep-link friendly counts',
      edgeCases: ['Timezone drift around week boundaries.', 'Empty recent activity should stay calm, not broken.'],
      acceptanceCriteria: [
        'Admin sees team-wide open work.',
        'Developer totals are scoped to their assignments.',
        'Completed count resets each Monday UTC.',
      ],
      regressionRisks: 'Unscoped totalTasks would leak org size to developers.',
      status: 'ready' as const,
      createdBy: adminId,
      approvedBy: null,
      approvedAt: null,
      archivedAt: null,
      tasks: [] as unknown[],
    },
    {
      title: 'Notification preferences',
      businessGoal: 'People should control which in-app alerts they actually receive.',
      technicalApproach:
        'Store notification toggles on the user preferences document and filter publishers before creating Notification rows.',
      apiDesign: 'PATCH /auth/preferences · GET /notifications · PATCH /notifications/:id/read',
      edgeCases: ['Mention alerts stay on even when comment alerts are off.', 'Unread badge must not count filtered types.'],
      acceptanceCriteria: [
        'Toggles persist across reload.',
        'Assignment alerts respect the taskAssigned flag.',
        'Mark-all-read clears only the current user’s inbox.',
      ],
      regressionRisks: 'Mongoose nested prefs need markModified or deep merge — shallow set silently no-ops.',
      status: 'draft' as const,
      createdBy: adminId,
      approvedBy: null,
      approvedAt: null,
      archivedAt: null,
      tasks: [] as unknown[],
    },
    {
      title: 'Legacy CSV export (archived)',
      businessGoal: 'One-off export of closed Q1 specs for compliance.',
      technicalApproach: 'Stream specs as CSV with optional includeArchived.',
      apiDesign: 'GET /specs/export.csv?includeArchived=true',
      edgeCases: ['Export cap at 500 rows.'],
      acceptanceCriteria: ['Archived specs appear when requested.', 'UTF-8 BOM optional for Excel.'],
      regressionRisks: 'Large exports can block the event loop without streaming.',
      status: 'approved' as const,
      createdBy: adminId,
      approvedBy: adminId,
      approvedAt: daysFromNow(-40),
      archivedAt: daysFromNow(-30),
      tasks: [] as unknown[],
    },
  ]

  const tasks = [
    {
      title: 'Store refresh tokens in httpOnly cookies',
      description: 'Stop writing session secrets to localStorage. Cookie must work behind the Vercel `/api` proxy.',
      status: 'done' as const,
      priority: 'high' as const,
      assignedTo: developerId,
      createdBy: adminId,
      tags: ['auth', 'security'],
      dueDate: daysFromNow(-14),
      watchers: [adminId],
      checklist: checklist('tests', 'pr', 'reviewed'),
      externalUrl: 'https://github.com/example/spec-flow/pull/12',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 0,
    },
    {
      title: 'Reject reused refresh tokens',
      description: 'Increment tokenVersion on every refresh and logout. Cover the concurrent refresh race in tests.',
      status: 'in-progress' as const,
      priority: 'critical' as const,
      assignedTo: developerId,
      createdBy: adminId,
      tags: ['auth', 'security'],
      dueDate: daysFromNow(2),
      watchers: [adminId, developerId],
      checklist: checklist('tests'),
      externalUrl: 'https://github.com/example/spec-flow/pull/18',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 0,
    },
    {
      title: 'Document demo accounts',
      description: 'Keep README credentials and seed notes accurate for portfolio reviewers.',
      status: 'backlog' as const,
      priority: 'low' as const,
      assignedTo: null,
      createdBy: adminId,
      tags: ['docs'],
      dueDate: daysFromNow(10),
      watchers: [],
      checklist: checklist(),
      externalUrl: '',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 0,
    },
    {
      title: 'Link task from spec detail',
      description: 'Admin picks an existing task and attaches it to the current spec without leaving the page.',
      status: 'in-review' as const,
      priority: 'medium' as const,
      assignedTo: adminId,
      createdBy: adminId,
      tags: ['specs', 'ui'],
      dueDate: daysFromNow(1),
      watchers: [developerId],
      checklist: checklist('tests', 'pr'),
      externalUrl: 'https://www.figma.com/file/demo/spec-link',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 1,
    },
    {
      title: 'Board columns for every status',
      description: 'Ensure backlog through done all render with seeded work and optimistic drag updates.',
      status: 'backlog' as const,
      priority: 'medium' as const,
      assignedTo: developerId,
      createdBy: adminId,
      tags: ['board', 'ui'],
      dueDate: daysFromNow(-2),
      watchers: [adminId],
      checklist: checklist(),
      externalUrl: '',
      blockedReason: 'Waiting on link-task UX copy before polishing empty board columns.',
      blockedByTitles: ['Link task from spec detail'],
      specIndex: 1,
    },
    {
      title: 'Show coverage on specs list',
      description: 'Surface linked task counts and status mix so PMs see handoff progress.',
      status: 'in-progress' as const,
      priority: 'high' as const,
      assignedTo: developerId,
      createdBy: adminId,
      tags: ['specs'],
      dueDate: daysFromNow(5),
      watchers: [adminId],
      checklist: checklist('tests'),
      externalUrl: '',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 1,
    },
    {
      title: 'Polish dashboard empty states',
      description: 'Show a calm empty state when recent activity is missing instead of a blank panel.',
      status: 'done' as const,
      priority: 'low' as const,
      assignedTo: developerId,
      createdBy: adminId,
      tags: ['ui', 'dashboard'],
      dueDate: daysFromNow(-7),
      watchers: [],
      checklist: checklist('tests', 'pr', 'reviewed'),
      externalUrl: '',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 2,
    },
    {
      title: 'Wire overdue and due-soon cards',
      description: 'Deep-link dashboard chips into the tasks list with due=overdue and due=soon query params.',
      status: 'in-progress' as const,
      priority: 'high' as const,
      assignedTo: adminId,
      createdBy: adminId,
      tags: ['dashboard'],
      dueDate: daysFromNow(3),
      watchers: [developerId],
      checklist: checklist(),
      externalUrl: '',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 2,
    },
    {
      title: 'Scope developer dashboard totals',
      description: 'totalTasks and openTasks must not leak org-wide counts to developers.',
      status: 'backlog' as const,
      priority: 'critical' as const,
      assignedTo: developerId,
      createdBy: adminId,
      tags: ['security', 'dashboard'],
      dueDate: daysFromNow(7),
      watchers: [adminId],
      checklist: checklist(),
      externalUrl: '',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 2,
    },
    {
      title: 'Preferences form for notification toggles',
      description: 'Settings → Notifications should PATCH preferences and toast on success.',
      status: 'in-review' as const,
      priority: 'medium' as const,
      assignedTo: developerId,
      createdBy: adminId,
      tags: ['settings', 'ui'],
      dueDate: daysFromNow(4),
      watchers: [adminId],
      checklist: checklist('tests', 'pr'),
      externalUrl: 'https://github.com/example/spec-flow/pull/24',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 3,
    },
    {
      title: 'Filter notify publishers by prefs',
      description: 'Skip Notification.create when the recipient disabled that event type.',
      status: 'backlog' as const,
      priority: 'high' as const,
      assignedTo: null,
      createdBy: adminId,
      tags: ['backend'],
      dueDate: null,
      watchers: [developerId],
      checklist: checklist(),
      externalUrl: '',
      blockedReason: 'Needs the preferences form merged first.',
      blockedByTitles: ['Preferences form for notification toggles'],
      specIndex: 3,
    },
    {
      title: 'One-off archived export smoke test',
      description: 'Confirm includeArchived returns the legacy CSV row for auditors.',
      status: 'done' as const,
      priority: 'low' as const,
      assignedTo: adminId,
      createdBy: adminId,
      tags: ['export'],
      dueDate: daysFromNow(-35),
      watchers: [],
      checklist: checklist('tests', 'pr', 'reviewed'),
      externalUrl: '',
      blockedReason: '',
      blockedByTitles: [] as string[],
      specIndex: 4,
    },
  ]

  const comments = [
    {
      parent: 'task' as const,
      title: 'Store refresh tokens in httpOnly cookies',
      author: 'admin' as const,
      body: 'Cookie path and Secure flags look right for production. Nice work on the proxy path.',
      mention: null as 'admin' | 'developer' | null,
    },
    {
      parent: 'task' as const,
      title: 'Store refresh tokens in httpOnly cookies',
      author: 'developer' as const,
      body: 'Verified the refresh call does not go through the axios interceptor retry loop.',
      mention: null,
    },
    {
      parent: 'task' as const,
      title: 'Reject reused refresh tokens',
      author: 'admin' as const,
      body: '@Jordan Lee please add a regression note when tokenVersion bumps — we burned a day on that once.',
      mention: 'developer' as const,
    },
    {
      parent: 'task' as const,
      title: 'Link task from spec detail',
      author: 'developer' as const,
      body: 'UI looks good; waiting on the final empty-state copy before I move this to done.',
      mention: null,
    },
    {
      parent: 'task' as const,
      title: 'Board columns for every status',
      author: 'developer' as const,
      body: 'Blocked on the link-task copy. Drag feels fine on desktop.',
      mention: null,
    },
    {
      parent: 'task' as const,
      title: 'Preferences form for notification toggles',
      author: 'admin' as const,
      body: '@Jordan Lee can you mirror the toggle size we used on Defaults?',
      mention: 'developer',
    },
    {
      parent: 'spec' as const,
      title: 'Spec to board handoff',
      author: 'developer' as const,
      body: 'Coverage chip on the list helped in the last review. Ready for approval after the board polish lands.',
      mention: null,
    },
    {
      parent: 'spec' as const,
      title: 'Refresh token rotation',
      author: 'admin' as const,
      body: 'Approved after the partitioned-cookie chase. Keep the `/api` proxy documented for the next deploy.',
      mention: null,
    },
  ]

  const revisions = [
    {
      specTitle: 'Refresh token rotation',
      version: 1,
      createdBy: adminId,
      status: 'approved' as const,
      title: 'Refresh token rotation',
      businessGoal: 'Keep sessions short-lived without forcing people to sign in every fifteen minutes.',
      technicalApproach: 'Issue a 15 minute access token and rotate a 7 day refresh token in an httpOnly cookie.',
      apiDesign: 'POST /auth/login, POST /auth/refresh, POST /auth/logout.',
      edgeCases: ['Reuse of a rotated refresh token is rejected.', 'Logout increments the token version.'],
      acceptanceCriteria: ['Access tokens expire in 15 minutes.', 'Refresh tokens are not readable from JavaScript.'],
      regressionRisks: 'A bad cookie domain would sign every user out on deploy.',
    },
    {
      specTitle: 'Legacy CSV export (archived)',
      version: 1,
      createdBy: adminId,
      status: 'approved' as const,
      title: 'Legacy CSV export (archived)',
      businessGoal: 'One-off export of closed Q1 specs for compliance.',
      technicalApproach: 'Stream specs as CSV with optional includeArchived.',
      apiDesign: 'GET /specs/export.csv?includeArchived=true',
      edgeCases: ['Export cap at 500 rows.'],
      acceptanceCriteria: ['Archived specs appear when requested.'],
      regressionRisks: 'Large exports can block the event loop without streaming.',
    },
  ]

  const notifications = [
    {
      user: 'developer' as const,
      type: 'task.assigned' as const,
      message: 'Alex Rivera assigned you “Reject reused refresh tokens”',
      taskTitle: 'Reject reused refresh tokens',
      read: false,
    },
    {
      user: 'developer' as const,
      type: 'mention.created' as const,
      message: 'Alex Rivera mentioned you on “Reject reused refresh tokens”',
      taskTitle: 'Reject reused refresh tokens',
      read: false,
    },
    {
      user: 'developer' as const,
      type: 'comment.created' as const,
      message: 'New comment on “Link task from spec detail”',
      taskTitle: 'Link task from spec detail',
      read: true,
    },
    {
      user: 'admin' as const,
      type: 'task.status' as const,
      message: 'Jordan Lee moved “Show coverage on specs list” to in-progress',
      taskTitle: 'Show coverage on specs list',
      read: false,
    },
    {
      user: 'admin' as const,
      type: 'task.assigned' as const,
      message: 'You assigned yourself “Wire overdue and due-soon cards”',
      taskTitle: 'Wire overdue and due-soon cards',
      read: true,
    },
  ]

  const activities = [
    {
      actor: 'admin' as const,
      type: 'spec.status' as const,
      specTitle: 'Refresh token rotation',
      taskTitle: null as string | null,
      meta: { from: 'in-review', to: 'approved', title: 'Refresh token rotation' },
    },
    {
      actor: 'admin' as const,
      type: 'task.created' as const,
      taskTitle: 'Reject reused refresh tokens',
      specTitle: null,
      meta: { title: 'Reject reused refresh tokens' },
    },
    {
      actor: 'admin' as const,
      type: 'task.assigned' as const,
      taskTitle: 'Reject reused refresh tokens',
      specTitle: null,
      meta: { userId: developerId },
    },
    {
      actor: 'developer' as const,
      type: 'task.status' as const,
      taskTitle: 'Reject reused refresh tokens',
      specTitle: null,
      meta: { from: 'backlog', to: 'in-progress' },
    },
    {
      actor: 'developer' as const,
      type: 'comment.created' as const,
      taskTitle: 'Link task from spec detail',
      specTitle: null,
      meta: {},
    },
    {
      actor: 'admin' as const,
      type: 'task.status' as const,
      taskTitle: 'Store refresh tokens in httpOnly cookies',
      specTitle: null,
      meta: { from: 'in-review', to: 'done' },
    },
    {
      actor: 'developer' as const,
      type: 'task.status' as const,
      taskTitle: 'Show coverage on specs list',
      specTitle: null,
      meta: { from: 'backlog', to: 'in-progress' },
    },
    {
      actor: 'admin' as const,
      type: 'spec.status' as const,
      specTitle: 'Spec to board handoff',
      taskTitle: null,
      meta: { from: 'ready', to: 'in-review', title: 'Spec to board handoff' },
    },
  ]

  const savedFilters = [
    {
      user: 'admin' as const,
      name: 'Critical open',
      query: { status: '', priority: 'critical', assignedTo: '', q: '', due: '' },
    },
    {
      user: 'admin' as const,
      name: 'Overdue',
      query: { status: '', priority: '', assignedTo: '', q: '', due: 'overdue' },
    },
    {
      user: 'developer' as const,
      name: 'My in progress',
      query: { status: 'in-progress', priority: '', assignedTo: developerId, q: '', due: '' },
    },
    {
      user: 'developer' as const,
      name: 'Auth work',
      query: { status: '', priority: '', assignedTo: '', q: 'auth', due: '' },
    },
  ]

  return { specs, tasks, comments, revisions, notifications, activities, savedFilters }
}
